# CONFIGURACIÓN DE HYPRLOCK POR TWO5

background {
    monitor =
    # Ruta a tu imagen (basada en tu captura)
  path = /home/two5/Pictures/Imagenes/luna.jpg 
  color = rgba(25, 20, 20, 1.0)

  # Desenfoque equilibrado (No tan borroso)
  blur_passes = 1           # Una sola capa para no perder la forma
  blur_size = 4             # Tamaño reducido para mantener nitidez
  noise = 0.0117
  contrast = 0.9
  brightness = 0.5          # Oscurece el fondo para que el cuadro resalte
}

input-field {
  monitor =
  size = 250, 50            # Más ancho para mejor visibilidad
  outline_thickness = 3
  dots_size = 0.2
  dots_spacing = 0.15
  dots_center = true
  
  # Colores para que "salte" a la vista
  outer_color = rgb(151515)
  inner_color = rgb(200, 200, 200)
  font_color = rgb(10, 10, 10)
  
  fade_on_empty = false     # Mantiene el cuadro visible siempre
  placeholder_text = <i></i>
    
    position = 0, -20
    halign = center
    valign = center
}

# Reloj digital encima del cuadro (opcional pero recomendado)
label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = JetBrains Mono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
