general {
    lock_cmd = pidof hyprlock || hyprlock       # comando para bloquear
    before_sleep_cmd = loginctl lock-session    # bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # encender pantalla al despertar
}

listener {
    timeout = 180                                # 3 minutos (180 segundos)
    on-timeout = hyprlock                        # bloquear pantalla
}

listener {
    timeout = 210                                # 3.5 minutos
    on-timeout = hyprctl dispatch dpms off       # apagar monitor
    on-resume = hyprctl dispatch dpms on         # volver a encender al mover mouse
}
